### ISSUE TITLE
I click the "Show TriView" option in right-click-menu, but there's nothing happend.

### ISSUE THREAD

**Issue by iseki0** [JetBrains/jitwatch4i#1]
After I manually load the `hotspot_pid3708.log`, I click the "Show TriView" option, in the right-click menu, but there's nothing happend.
![image](https://github.com/user-attachments/assets/361b2262-9be7-4f4e-b718-9fa14630f88f).

Since I use gradle, I add the following configuration into `build.gradle.kts`:
```kotlin
tasks.withType<JavaExec>{
    jvmArgs("-XX:+UnlockDiagnosticVMOptions", "-XX:+PrintAssembly", "-XX:+LogCompilation")
}
```
My IDEA version:
```
IntelliJ IDEA 2024.3.1 (Ultimate Edition)
Build #IU-243.22562.145, built on December 9, 2024
Licensed to iseki wang
You have a perpetual fallback license for this version.
Subscription is active until December 15, 2025.
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 6000M
Cores: 8
Registry:
  ide.experimental.ui=true
  i18n.locale=
  org.toml.json.schema=false
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (242.241211.129)
  org.antlr.intellij.plugin (1.24)
  com.thvardhan.gradianto (5.5)
  com.jetbrains.space (243.21565.122)
  com.github.lppedd.idea-conventional-commit (0.23.1)
  PythonCore (243.22562.145)
  com.jetbrains.rust (243.22562.187)
  JitWatch4i (0.2.0)
  JOL (1.13.0)
  org.jetbrains.idea.grammar (2022.3.2)
  String Manipulation (9.15.0)
  org.jetbrains.plugins.go (243.22562.145)
  Pythonid (243.22562.145)
  org.antlr.jetbrains.st4plugin (0.10)
  com.intellij.ml.llm (243.22562.251.6)
  com.intellij.nativeDebug (243.22562.145)
  com.github.copilot (1.5.29.7524)
  zielu.gittoolbox (600.0.9+243)
Kotlin: 243.22562.145-IJ
```

[hotspot_pid3708.log](https://github.com/user-attachments/files/18161533/hotspot_pid3708.log)

**Comment by iseki0** [comment]
@skybber

**Comment by iseki0** [comment]
You might get the code here: iseki0/hashutil

**Comment by skybber** [comment]
Hi, thanks for report. The Triview feature remained from the migration of the JITWatch project, but it is not functional - I'll remove the popup menu. It has been replaced by the IntelliJ editor and the bytecode + assembly views.

**Comment by iseki0** [comment]
@skybber Thank you, I founded it. Is it a right side panel? And... the focusing is strange, when I click some lines in the right panel, it scrolled!

**Comment by skybber** [comment]
There is synchronization between editor and Bytecode/Assembly viewer, so when you move cursor in editor you should see corresponding bytecode or assembly. Assembly is visible when  `+XX:PrintAssembly ` is used, and also JDK must be compiled with hsdis (disassembler) support, otherwise there are hexacodes in the log file.
